### ISSUE TITLE
应该用哪个版本的JDK、Maven来编译成lib？

### ISSUE THREAD

**Issue by peterzh4ng** [su18/ysoserial#15]
请问一下，我目前想要基于su18版的ysoserial来做点小工具，但是我发现编译遇到个小问题，就是如果我用7及以上的jdk版本那么编译的时候会有一个ClassLoader类找不到，但是用6版本的JDK，IDEA又不支持，我该怎么办呢？

```
Executing pre-compile tasks...
Running 'before' tasks
Checking sources
Copying resources... [ysuserial]
Parsing java… [ysuserial]
java: An exception has occurred in the compiler (1.7.0_80). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java: java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/core/config/plugins/processor/PluginProcessor : Unsupported major.minor version 52.0
java: 	at java.lang.ClassLoader.defineClass1(Native Method)
java: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
java: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
java: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
java: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
java: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
java: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
java: 	at java.security.AccessController.doPrivileged(Native Method)
java: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
java: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
java: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
java: 	at org.jetbrains.jps.javac.LazyClassLoader.findClass(LazyClassLoader.java:58)
java: 	at java.lang.Class.forName0(Native Method)
java: 	at java.lang.Class.forName(Class.java:278)
java: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
java: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
java: 	at org.jetbrains.jps.javac.Iterators$11.next(Iterators.java:221)
java: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:614)
java: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:707)
java: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
java: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
java: 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
java: 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
java: 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
java: 	at com.sun.tools.javac.main.Main.compile(Main.java:439)
java: 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:239)
java: 	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:189)
java: 	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:28)
java: 	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:262)
java: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java: 	at java.lang.Thread.run(Thread.java:745)
java: Compilation failed: internal java compiler error
Checking dependencies… [ysuserial]
Dependency analysis found 0 affected files
Errors occurred while compiling module 'ysuserial'
javac 7 was used to compile java sources
Finished, saving caches…
Compilation failed: errors: 1; warnings: 0
Executing post-compile tasks...
Compilation failed: errors: 1; warnings: 0
Synchronizing output directories...
2023-04-18 10:57 PM - Build completed with 1 error and 0 warnings in 5 sec, 71 ms
```

**Comment by su18** [comment]
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /Users/su18/Software/apache-maven-3.8.6
Java version: 1.8.0_345, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "aarch64", family: "mac"


以上是我的信息仅供参考，目前仅针对我常用的 jdk 1.8 使用和开发，其他 JDK 版本没有使用和测试

**Comment by langyayue** [comment]
JDK可以使用1.8.0_241，完美运行
<img width="519" alt="image" src="https://user-images.githubusercontent.com/19259387/233021957-60b73d36-df83-4b7c-9e18-5f3d61e21a4c.png">

**Comment by peterzh4ng** [comment]
谢谢~，我用的版本是jdk8u322，降到8u181确实没什么问题。
